// src/LeafletMap.svelte
<script>
  import * as L from "leaflet";
  import { onMount } from "svelte";

  // props with default values in case none are passed in by a parent
  export let center = [0, 0];
  export let zoom = 1;
  export let title = "";

  let mapDomNode;

  onMount(() => {
    var map = L.map(mapDomNode).setView([center[1], center[0]], zoom);
    map.scrollWheelZoom.disable();
    map.attributionControl.setPrefix(false);

    L.tileLayer(
      "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
      {
        attribution:
          "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
      }
    ).addTo(map);
  });
</script>

<style global type="postcss">
  @import "leaflet";
  div.leafletMapWrapper,
  div.leafletMapWrapper div.map {
    width: 100%;
    height: 100%;
    position: relative;
  }
  div.leafletMapWrapper .title {
    position: absolute;
    top: 5px;
    right: 5px;
    z-index: 401;
    color: #fff;
    background-color: rgba(0, 0, 0, 0.65);
    padding: 4px 9px;
    font-weight: 100;
  }
</style>

<div class="leafletMapWrapper">
  <div class="map" bind:this={mapDomNode} />
  <div class="title">{title}</div>
</div>

// src/components/LeafletMap.vue
<template>
  <v-map :zoom="zoom" :center="center" :options="{scrollWheelZoom: false}">
    <v-tilelayer url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" attribution="Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community"></v-tilelayer>
  </v-map>
</template>

<script>
import { Map as VueMap, TileLayer, Marker } from 'vue2-leaflet';

export default {
  name: 'LeafletMap',
  data() {
    return {};
  },
  components: {
    'v-map': VueMap,
    'v-tilelayer': TileLayer,
  },
  props: {
    center: {
      type: Array,
      default: [-122, 38],
    },
    zoom: {
      type: Number,
      default: 8,
    },
    basemap: {
      type: String,
      required: true,
      default: 'streets',
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  @import "~leaflet/dist/leaflet.css";

  .component {
    background-color: gray;
    height: 100%;
  }
</style>
